# Generated by Django 5.1.2 on 2024-10-16 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminModel',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('admin_name', models.CharField(max_length=100)),
                ('admin_mail', models.EmailField(max_length=254)),
                ('admin_password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PickupModel',
            fields=[
                ('pickup_id', models.AutoField(primary_key=True, serialize=False)),
                ('mobile_no', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=100)),
                ('pickup_date', models.DateField()),
                ('pickup_time', models.TimeField()),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
