# Generated by Django 5.1.2 on 2024-10-24 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0003_jobpostmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpostmodel',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobpostmodel',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='jobpostmodel',
            name='desirable_skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobpostmodel',
            name='experience_required',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='jobpostmodel',
            name='job_type',
            field=models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract'), ('Internship', 'Internship')], max_length=50),
        ),
        migrations.AlterField(
            model_name='jobpostmodel',
            name='requirements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobpostmodel',
            name='responsibilities',
            field=models.TextField(blank=True, null=True),
        ),
    ]
