# Generated by Django 5.1.2 on 2024-10-24 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0004_jobpostmodel_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpostmodel',
            name='job_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
