# Generated by Django 5.1.2 on 2024-10-24 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0005_alter_jobpostmodel_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpostmodel',
            name='education',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobpostmodel',
            name='experience_required',
            field=models.TextField(blank=True, null=True),
        ),
    ]
