# Generated by Django 5.1.2 on 2024-10-25 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0006_alter_jobpostmodel_education_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplyModel',
            fields=[
                ('apply_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.CharField(max_length=50)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserApp.jobpostmodel')),
            ],
        ),
    ]
